// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQUPsaNiv0jlC6nqXCj-FAcYm4FpAqqo',
    appId: '1:996029238718:web:4551f3e124b9b61d8bbdef',
    messagingSenderId: '996029238718',
    projectId: 'tool-bocs-prod-v3',
    authDomain: 'tool-bocs-prod-v3.firebaseapp.com',
    storageBucket: 'tool-bocs-prod-v3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHO-qRyPYK7pSzWZ65qVMpiTNlgJYIZE',
    appId: '1:996029238718:android:ff94aba999a00e5f8bbdef',
    messagingSenderId: '996029238718',
    projectId: 'tool-bocs-prod-v3',
    storageBucket: 'tool-bocs-prod-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyigqnR42F1zhvBQNbyjxdtbT9Cr1Sd6U',
    appId: '1:996029238718:ios:c18a1088471078b38bbdef',
    messagingSenderId: '996029238718',
    projectId: 'tool-bocs-prod-v3',
    storageBucket: 'tool-bocs-prod-v3.firebasestorage.app',
    iosBundleId: 'com.example.toolucs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyigqnR42F1zhvBQNbyjxdtbT9Cr1Sd6U',
    appId: '1:996029238718:ios:c18a1088471078b38bbdef',
    messagingSenderId: '996029238718',
    projectId: 'tool-bocs-prod-v3',
    storageBucket: 'tool-bocs-prod-v3.firebasestorage.app',
    iosBundleId: 'com.example.toolucs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAQUPsaNiv0jlC6nqXCj-FAcYm4FpAqqo',
    appId: '1:996029238718:web:891f8affb8d6ea7f8bbdef',
    messagingSenderId: '996029238718',
    projectId: 'tool-bocs-prod-v3',
    authDomain: 'tool-bocs-prod-v3.firebaseapp.com',
    storageBucket: 'tool-bocs-prod-v3.firebasestorage.app',
  );

}